name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js app
        run: |
          npm run build
          echo Aplication Build SUCCESS

      - name: Install Amplify CLI
        run: |
          npm install -g @aws-amplify/cli
          echo CLI installed

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout Amplify env's
        run: |
          echo Checkout for env's start
          amplify env list
          echo Checkout for env's over

      - name: Amplify CLI - Publish
        run: |
          amplify pull --appId d7irc7oy3gqfl --envName dev
          amplify 
          amplify publish --yes
